### ISSUE TITLE
about premium user.

### ISSUE THREAD

**Issue by listmen001** [CDN18/Multigram#1]
what is the price for premiums?
And why are there only 20 accants?, and not 100?
Or confused what?
A friend advised me to try multigram.
He said that you can add 100 accounts.
Or did you mix up the repository?

**Comment by cdn0x12** [comment]
> what is the price for premiums?

The cost varies depending on your country.

> And why are there only 20 accants?, and not 100?

In theory, you could set the number to any value you prefer. The default limit is 3, which I think is too low.

>  He said that you can add 100 accounts.

Originally, the limit was set at 100, but since [Build20220701](https://github.com/CDN18/Multigram/releases/tag/Build20220701), it was reduced to 10 (The maximum number will be 20 if you log in 10 premium account, as 1 additional slot was granted per premium account). Logging into too many accounts in the same device could potentially pose additional risks to the account."

**Comment by listmen001** [comment]
> The cost varies depending on your country. 

specify the price in $.
That will be enough.
And so, I'm from a small country where the Internet is distributed only on Saturdays after lunch on a full moon, if there is no low tide and 100 eggs have been collected in the chicken coop.
If something is not fulfilled from the conditions, then there is no Internet until the next time :)
Therefore, there is no money, but you hold on, as they say :)

> Originally, the limit was set at 100, but since [Build20220701](https://github.com/CDN18/Multigram/releases/tag/Build20220701), it was reduced to 10 (The maximum number will be 20 if you log in 10 premium account, as 1 additional slot was granted per premium account). Logging into too many accounts in the same device could potentially pose additional risks to the account."

I have telegram accounts not for spam, but for subscriptions and confirmations that I already have an account.
that's all.
Therefore, if you consider that on a Xiaomi smartphone you can make a duplicate application once, then when you log in with 100 accounts into one, you can log in with another 100 accounts (this is a built-in function and very convenient, it works without third-party applications).
If I add my own proxy to each account, then everything will be fine.
The calculation is based on the convenience of work.
Plus, there are currently no 100-200 accounts so far.
but they will.
I plan that there will be live pictures that will be at hand for each account.

P.S.: notifications on github work very strangely, until I looked at the notifications - nothing came.

**Comment by listmen001** [comment]
All accounts have been blocked today. exactly the ones that came with logging into the app.

**Comment by cdn0x12** [comment]
> specify the price in $.
> That will be enough.

Even if the currency is specified, the price can still vary. Currently, the price of Telegram Premium is around $5 per month. For users in developing countries, the rate should be cheaper.

> All accounts have been blocked today. exactly the ones that came with logging into the app.

You could try switching to a different client. If the account suspension issue still occurs, then it might be due to other reasons.

---

I will now close this issue. If you have any other questions, feel free to continue commenting.
